name: Feature request
description: Suggest an idea for this project
labels: [ "type/feature" ]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What should change and why?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any related issues, links, or constraints.
