name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate changelog (basic)
        id: notes
        run: |
          echo "## Changes" > NOTES.md
          git log --pretty=format:'- %s (%h)' $(git describe --tags --abbrev=0 --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "")..HEAD >> NOTES.md || true

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          body_path: NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
